FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# collective

Design Collective API Documentation.

## Pages Collection [/pages]

### List All Questions [GET]

+ Response 200 (application/json)

    {  
       "pages":[  
          {  
             "id":2,
             "name":"members",
             "title":"Members",
             "menu_title":"Members",
             "slug":null,
             "show_in_menu":true,
             "ancestry":null,
             "view_template":"members",
             "created_at":"2016-03-19T05:34:06.094Z",
             "updated_at":"2016-03-19T05:34:06.094Z",
             "blocks":[]
          },
          {  
             "id":1,
             "name":"homepage",
             "title":"Homepage",
             "menu_title":"Homepage",
             "slug":null,
             "show_in_menu":true,
             "ancestry":null,
             "view_template":"homepage",
             "created_at":"2016-03-19T05:34:05.642Z",
             "updated_at":"2016-03-19T05:34:05.642Z",
             "blocks":[]
          },
          {  
             "id":3,
             "name":"about",
             "title":"About",
             "menu_title":"About",
             "slug":null,
             "show_in_menu":true,
             "ancestry":null,
             "view_template":"default",
             "created_at":"2016-03-19T07:30:09.215Z",
             "updated_at":"2016-03-19T08:34:50.795Z",
             "blocks":[  
                {  
                   "name":"hero_title",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"featured_work_stats",
                   "type":"Spina::Structure"
                },
                {  
                   "name":"slider",
                   "type":"Spina::PhotoCollection",
                   "fields":[  
                      "id",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"hero_subtitle",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"hero_background_video",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"text",
                   "type":"Spina::Text",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"include_title",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"include_subtitle",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"include_background_image",
                   "type":"Spina::Photo"
                },
                {  
                   "name":"include_image",
                   "type":"Spina::Photo"
                },
                {  
                   "name":"include_text",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"include_classes",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"include_button_label",
                   "type":"Spina::Line",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"primary_color",
                   "type":"Spina::Color",
                   "fields":[  
                      "id",
                      "content",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"hero_background_image",
                   "type":"Spina::Photo",
                   "fields":[  
                      "id",
                      "file",
                      "created_at",
                      "updated_at"
                   ]
                },
                {  
                   "name":"sections",
                   "type":"Spina::Structure",
                   "fields":[  
                      "id",
                      "created_at",
                      "updated_at"
                   ]
                    }
                 ]
              },
              {  
                 "id":4,
                 "name":"clients",
                 "title":"Clients",
                 "menu_title":"Clients",
                 "slug":null,
                 "show_in_menu":true,
                 "ancestry":null,
                 "view_template":"work",
                 "created_at":"2016-03-19T07:30:09.233Z",
                 "updated_at":"2016-03-19T15:04:32.300Z",
                 "blocks":[  
                    {  
                       "name":"hero_title",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"featured_work_stats",
                       "type":"Spina::Structure"
                    },
                    {  
                       "name":"slider",
                       "type":"Spina::PhotoCollection",
                       "fields":[  
                          "id",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"hero_subtitle",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"hero_background_image",
                       "type":"Spina::Photo"
                    },
                    {  
                       "name":"hero_background_video",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"text",
                       "type":"Spina::Text",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"include_title",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"include_subtitle",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"include_background_image",
                       "type":"Spina::Photo"
                    },
                    {  
                       "name":"include_image",
                       "type":"Spina::Photo"
                    },
                    {  
                       "name":"include_text",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"include_classes",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"include_button_label",
                       "type":"Spina::Line",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    },
                    {  
                       "name":"sections",
                       "type":"Spina::Structure"
                    },
                    {  
                       "name":"primary_color",
                       "type":"Spina::Color",
                       "fields":[  
                          "id",
                          "content",
                          "created_at",
                          "updated_at"
                       ]
                    }
                 ]
              },
              {  
                 "id":5,
                 "name":"process",
                 "title":"Process",
                 "menu_title":"Process",
                 "slug":null,
                 "show_in_menu":true,
                 "ancestry":null,
                 "view_template":"default",
                 "created_at":"2016-03-19T07:30:09.242Z",
                 "updated_at":"2016-03-19T07:30:09.242Z",
                 "blocks":[]
              },
              {  
                 "id":6,
                 "name":"portfolio",
                 "title":"Portfolio",
                 "menu_title":"Portfolio",
                 "slug":null,
                 "show_in_menu":true,
                 "ancestry":null,
                 "view_template":"default",
                 "created_at":"2016-03-19T07:30:09.251Z",
                 "updated_at":"2016-03-19T07:30:09.251Z",
                 "blocks":[]
              },
              {  
                 "id":7,
                 "name":"blog",
                 "title":"Blog",
                 "menu_title":"Blog",
                 "slug":null,
                 "show_in_menu":true,
                 "ancestry":null,
                 "view_template":"default",
                 "created_at":"2016-03-19T07:30:09.267Z",
                 "updated_at":"2016-03-19T07:30:09.267Z",
                 "blocks":[]
              },
              {  
                 "id":8,
                 "name":"contact",
                 "title":"Contact",
                 "menu_title":"Contact",
                 "slug":null,
                 "show_in_menu":true,
                 "ancestry":null,
                 "view_template":"default",
                 "created_at":"2016-03-19T07:30:09.277Z",
                 "updated_at":"2016-03-19T07:30:09.277Z",
                 "blocks":[]
              }
           ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /pages/3

    + Body

            {  
                "page":{  
                    "id":3,
                    "name":"about",
                    "slug":null,
                    "title":"About",
                    "menu_title":"About",
                    "seo_title":"About",
                    "description":"",
                    "show_in_menu":true,
                    "ancestry":null,
                    "view_template":"default",
                    "created_at":"2016-03-19T07:30:09.215Z",
                    "updated_at":"2016-03-19T08:34:50.795Z"
                },
                "blocks":[  
                    {  
                        "name":"hero_title",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":1,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.799Z",
                            "updated_at":"2016-03-19T08:34:50.799Z"
                        }
                    },
                    {  
                        "name":"featured_work_stats",
                        "type":"Spina::Structure",
                        "fields":null
                    },
                    {  
                        "name":"slider",
                        "type":"Spina::PhotoCollection",
                        "fields":{  
                            "id":1,
                            "created_at":"2016-03-19T08:34:50.809Z",
                            "updated_at":"2016-03-19T08:34:50.809Z"
                        }
                    },
                    {  
                        "name":"hero_subtitle",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":2,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.815Z",
                            "updated_at":"2016-03-19T08:34:50.815Z"
                        }
                    },
                    {  
                        "name":"hero_background_video",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":3,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.825Z",
                            "updated_at":"2016-03-19T08:34:50.825Z"
                        }
                    },
                    {  
                        "name":"text",
                        "type":"Spina::Text",
                        "fields":{  
                            "id":1,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.829Z",
                            "updated_at":"2016-03-19T08:34:50.829Z"
                        }
                    },
                    {  
                        "name":"include_title",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":4,
                            "content":"We are",
                            "created_at":"2016-03-19T08:34:50.837Z",
                            "updated_at":"2016-03-19T08:34:50.837Z"
                        }
                    },
                    {  
                        "name":"include_subtitle",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":5,
                            "content":"Believers. Dreamers. Designers.",
                            "created_at":"2016-03-19T08:34:50.842Z",
                            "updated_at":"2016-03-19T08:34:50.842Z"
                        }
                    },
                    {  
                        "name":"include_background_image",
                        "type":"Spina::Photo",
                        "fields":null
                    },
                    {  
                        "name":"include_image",
                        "type":"Spina::Photo",
                        "fields":null
                    },
                    {  
                        "name":"include_text",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":6,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.852Z",
                            "updated_at":"2016-03-19T08:34:50.852Z"
                        }
                    },
                    {  
                        "name":"include_classes",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":7,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.858Z",
                            "updated_at":"2016-03-19T08:34:50.858Z"
                        }
                    },
                    {  
                        "name":"include_button_label",
                        "type":"Spina::Line",
                        "fields":{  
                            "id":8,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.862Z",
                            "updated_at":"2016-03-19T08:34:50.862Z"
                        }
                    },
                    {  
                        "name":"primary_color",
                        "type":"Spina::Color",
                        "fields":{  
                            "id":1,
                            "content":"",
                            "created_at":"2016-03-19T08:34:50.868Z",
                            "updated_at":"2016-03-19T08:34:50.868Z"
                        }
                    },
                    {  
                        "name":"hero_background_image",
                        "type":"Spina::Photo",
                        "fields":{  
                            "id":1,
                            "file":{  
                                "url":"/uploads/spina/photo/file/1/photo-1414849424631-8b18529a81ca.jpg",
                                "image":{  
                                    "url":"/uploads/spina/photo/file/1/image_photo-1414849424631-8b18529a81ca.jpg"
                                },
                                "thumb":{  
                                    "url":"/uploads/spina/photo/file/1/thumb_photo-1414849424631-8b18529a81ca.jpg"
                                }
                            },
                            "created_at":"2016-03-19T08:51:23.692Z",
                            "updated_at":"2016-03-19T08:51:23.692Z"
                        }
                    },
                    {  
                        "name":"sections",
                        "type":"Spina::Structure",
                        "fields":{  
                            "id":1,
                            "created_at":"2016-03-19T09:04:03.951Z",
                            "updated_at":"2016-03-19T09:04:03.951Z"
                        },
                        "structure":[  
                            {  
                                "structure":{  
                                    "structure_id":1,
                                    "id":1,
                                    "position":null,
                                    "created_at":"2016-03-19T09:04:03.954Z",
                                    "updated_at":"2016-03-19T09:04:03.954Z"
                                },
                                "fields":[  
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":1,
                                            "structure_partable_id":9,
                                            "structure_partable_type":"Spina::Line",
                                            "name":"large_title",
                                            "title":"Large title",
                                            "created_at":"2016-03-19T09:04:03.963Z",
                                            "updated_at":"2016-03-19T09:04:03.963Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":2,
                                            "structure_partable_id":10,
                                            "structure_partable_type":"Spina::Line",
                                            "name":"small_title",
                                            "title":"Small title",
                                            "created_at":"2016-03-19T09:04:03.970Z",
                                            "updated_at":"2016-03-19T09:04:03.970Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":3,
                                            "structure_partable_id":2,
                                            "structure_partable_type":"Spina::Photo",
                                            "name":"section_background_image",
                                            "title":"Section background image",
                                            "created_at":"2016-03-19T09:04:03.973Z",
                                            "updated_at":"2016-03-19T09:04:03.973Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":4,
                                            "structure_partable_id":2,
                                            "structure_partable_type":"Spina::Text",
                                            "name":"text",
                                            "title":"Text",
                                            "created_at":"2016-03-19T09:04:03.981Z",
                                            "updated_at":"2016-03-19T09:04:03.981Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":5,
                                            "structure_partable_id":null,
                                            "structure_partable_type":"Spina::Photo",
                                            "name":"section_image",
                                            "title":"Section image",
                                            "created_at":"2016-03-19T09:04:03.984Z",
                                            "updated_at":"2016-03-19T09:04:03.984Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":1,
                                            "id":6,
                                            "structure_partable_id":3,
                                            "structure_partable_type":"Spina::Text",
                                            "name":"section_links",
                                            "title":"Section links",
                                            "created_at":"2016-03-19T09:04:03.990Z",
                                            "updated_at":"2016-03-19T09:04:03.990Z"
                                        }
                                    }
                                ]
                            },
                            {  
                                "structure":{  
                                    "structure_id":1,
                                    "id":2,
                                    "position":null,
                                    "created_at":"2016-03-19T13:53:54.009Z",
                                    "updated_at":"2016-03-19T13:53:54.009Z"
                                },
                                "fields":[  
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":7,
                                            "structure_partable_id":11,
                                            "structure_partable_type":"Spina::Line",
                                            "name":"large_title",
                                            "title":"Large title",
                                            "created_at":"2016-03-19T13:53:54.039Z",
                                            "updated_at":"2016-03-19T13:53:54.039Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":8,
                                            "structure_partable_id":12,
                                            "structure_partable_type":"Spina::Line",
                                            "name":"small_title",
                                            "title":"Small title",
                                            "created_at":"2016-03-19T13:53:54.064Z",
                                            "updated_at":"2016-03-19T13:53:54.064Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":9,
                                            "structure_partable_id":null,
                                            "structure_partable_type":"Spina::Photo",
                                            "name":"section_background_image",
                                            "title":"Section background image",
                                            "created_at":"2016-03-19T13:53:54.079Z",
                                            "updated_at":"2016-03-19T13:53:54.079Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":10,
                                            "structure_partable_id":4,
                                            "structure_partable_type":"Spina::Text",
                                            "name":"text",
                                            "title":"Text",
                                            "created_at":"2016-03-19T13:53:54.106Z",
                                            "updated_at":"2016-03-19T13:53:54.106Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":11,
                                            "structure_partable_id":null,
                                            "structure_partable_type":"Spina::Photo",
                                            "name":"section_image",
                                            "title":"Section image",
                                            "created_at":"2016-03-19T13:53:54.124Z",
                                            "updated_at":"2016-03-19T13:53:54.124Z"
                                        }
                                    },
                                    {  
                                        "field":{  
                                            "structure_item_id":2,
                                            "id":12,
                                            "structure_partable_id":5,
                                            "structure_partable_type":"Spina::Text",
                                            "name":"section_links",
                                            "title":"Section links",
                                            "created_at":"2016-03-19T13:53:54.153Z",
                                            "updated_at":"2016-03-19T13:53:54.153Z"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }