# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b5dfa66dcb9985080786a7ef91dc3a4cb512f6148a14181a777b2d91ae6c3990563020d560bb365384a8c220df71f08314672fc5cb5cfb34f570e763ba55d7

test:
  secret_key_base: bc8f075f8c0fe840e17816a1f1dba1c1795355d8c2422707afecda8f0a3610d7bf405432746394d734fcfb09ac82ead636415b9e22be28b411db8b57a0a8dff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
